# Generated by Django 4.2.16 on 2025-06-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimenapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stopword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopwords', models.CharField(max_length=255)),
            ],
        ),
    ]
