# Generated by Django 5.2.3 on 2025-06-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimenapp', '0002_stopword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preprocessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_folding', models.CharField(max_length=255, null=True)),
                ('tokenizing', models.CharField(max_length=255, null=True)),
                ('stopword_removal', models.CharField(max_length=255, null=True)),
                ('stemming', models.CharField(max_length=255, null=True)),
                ('lemmatizing', models.CharField(max_length=255, null=True)),
                ('text_bersih', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slangword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katabaku', models.CharField(max_length=255)),
                ('katatidakbaku', models.CharField(max_length=255)),
            ],
        ),
    ]
