# Generated by Django 5.2.3 on 2025-06-29 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentimenapp', '0003_preprocessing_slangword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preprocessing',
            new_name='PreprocessingModel',
        ),
    ]
