# Generated by Django 5.2.3 on 2025-06-29 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentimenapp', '0004_rename_preprocessing_preprocessingmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preprocessingmodel',
            name='lemmatizing',
        ),
    ]
