# Generated by Django 5.2.3 on 2025-06-29 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimenapp', '0005_remove_preprocessingmodel_lemmatizing'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprocessingmodel',
            name='teks_awal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sentimenapp.datateks'),
        ),
    ]
