# Generated by Django 5.2.3 on 2025-06-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimenapp', '0006_preprocessingmodel_teks_awal'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprocessingmodel',
            name='slangword_removal',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
