# Generated by Django 5.2.3 on 2025-06-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimenapp', '0007_preprocessingmodel_slangword_removal'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprocessingmodel',
            name='symbol_removal',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
