# Generated by Django 5.2.3 on 2025-06-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimenapp', '0008_preprocessingmodel_symbol_removal'),
    ]

    operations = [
        migrations.AddField(
            model_name='datateks',
            name='label',
            field=models.CharField(choices=[('netral', 'Netral'), ('positif', 'Positif'), ('negatif', 'Negatif')], max_length=255, null=True),
        ),
    ]
