# Generated by Django 5.2.3 on 2025-07-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimenapp', '0009_datateks_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datateks',
            name='label',
            field=models.CharField(choices=[('netral', 'Netral'), ('negatif', 'Negatif'), ('positif', 'Positif')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preprocessingmodel',
            name='case_folding',
            field=models.TextField(null=True),
        ),
    ]
