# Generated by Django 5.2.3 on 2025-07-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimenapp', '0010_alter_datateks_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datateks',
            name='label',
            field=models.CharField(choices=[('netral', 'Netral'), ('positif', 'Positif'), ('negatif', 'Negatif')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preprocessingmodel',
            name='slangword_removal',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='preprocessingmodel',
            name='stemming',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='preprocessingmodel',
            name='stopword_removal',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='preprocessingmodel',
            name='text_bersih',
            field=models.TextField(null=True),
        ),
    ]
