# Generated by Django 5.2.3 on 2025-07-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimenapp', '0012_alter_datateks_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datateks',
            name='label',
            field=models.CharField(choices=[('positif', 'Positif'), ('netral', 'Netral'), ('negatif', 'Negatif')], max_length=255, null=True),
        ),
    ]
