# Generated by Django 5.2.3 on 2025-07-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimenapp', '0013_alter_datateks_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprocessingmodel',
            name='label',
            field=models.CharField(choices=[('netral', 'Netral'), ('negatif', 'Negatif'), ('positif', 'Positif')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datateks',
            name='label',
            field=models.CharField(choices=[('netral', 'Netral'), ('negatif', 'Negatif'), ('positif', 'Positif')], max_length=255, null=True),
        ),
    ]
