# Generated by Django 5.2.3 on 2025-07-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimenapp', '0014_preprocessingmodel_label_alter_datateks_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datateks',
            name='label',
        ),
        migrations.AlterField(
            model_name='preprocessingmodel',
            name='label',
            field=models.CharField(choices=[('negatif', 'Negatif'), ('positif', 'Positif'), ('netral', 'Netral')], max_length=255, null=True),
        ),
    ]
